### PR TITLE
spinout runtime module

### PR DESCRIPTION
**Pull request by odeke-em**
Creates a vanity URL for the cosmos-sdk package "runtime", accessible by URL "cosmossdk.io/runtime".

Updates https://github.com/cosmos/cosmos-sdk/issues/18411

### CODE REVIEW

**Comment by odeke-em** [comment]
Kindly cc-ing @julienrbrt @tac0turtle

**Comment by julienrbrt** [comment]
I don't think we should spin out runtime just yet. It will be modified with our server/app manager work.

**Comment by julienrbrt** [comment]
Additionally, maybe we should slow down and start instead removing the circular dependencies in modules instead? I am currently doing the removal of bank as import in the SDK. But we have some modules importing each other as well for tests only, and we should delete that.

I am personally afraid that keeping pulling out stuff will before we get a dependency graph fixed will complicate our life.

ref: https://github.com/cosmos/cosmos-sdk/issues/18290

**Comment by odeke-em** [comment]
Hey @julienrbrt sure I can help out with that dependency pruning but I wanted to ensure that I got this done once and for all so the PR is up https://github.com/cosmos/cosmos-sdk/pull/18412. We can label it as "DO NOT MERGE" until we've cleared up dependencies in the go.mod file.

**Pull request closed without merging**
